name: dbt CD

on:
  push:
    branches: [main]

jobs:
  dbt-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt-duckdb
        run: pip install dbt-duckdb==1.10.1

      - name: Create profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOF
          dbt_project:
            target: prod
            outputs:
              prod:
                type: duckdb
                path: prod.duckdb
                threads: 4
                schema: prod
          EOF

      - name: Install dependencies
        run: dbt deps

      - name: Debug
        run: dbt debug --target prod

      - name: Build
        run: dbt build --target prod